cricket/urls.py
from django.contrib import admin
from django.urls import path,include
from cricket import views

urlpatterns = [
    path('',  views.team_list,name='team_list'),
    path('team_detail/<int:pk>',  views.team_detail,name='team_detail'),
    path('matches',  views.fixture,name='matches'),
    path('points',  views.points_table,name='points'),
]

app_name = 'cricket'

cricket_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cricket.urls',namespace='cricket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

cricket/models.py
from django.db import models

# Create your models here.

class Team(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    captain = models.CharField(max_length=100, blank=True, null=True)
    vice_captain = models.CharField(max_length=100, blank=True, null=True)
    coach = models.CharField(max_length=100, blank=True, null=True)
    owner = models.CharField(max_length=100, blank=True, null=True)
    logo = models.ImageField(upload_to="team_logo")
    club = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        
    def __str__(self):
        return self.name

class Player(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    age = models.PositiveIntegerField()
    dob = models.DateField()
    total_run = models.PositiveIntegerField(default=0)
    total_wicket = models.PositiveIntegerField(default=0)
    total_match = models.PositiveIntegerField(default=0)
    highest_score = models.PositiveIntegerField(default=0)
    fifties = models.PositiveIntegerField(default=0)
    hundreds = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to="player")
    jursey_number = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=50, blank=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name        

class Match(models.Model):
    match_number = models.PositiveIntegerField(default=0)
    match_type = models.CharField(max_length=100, blank=True)
    team1 = models.ForeignKey(Team,  related_name='teamone', on_delete=models.CASCADE)
    team2 = models.ForeignKey(Team,  related_name='teamtwo', on_delete=models.CASCADE)
    winner = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now=False)
    description = models.TextField(blank=True) 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
       
    def __str__(self):
        return self.winner      
       

class Point(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    play = models.PositiveIntegerField(default=0)
    won = models.PositiveIntegerField(default=0)
    lost = models.PositiveIntegerField(default=0)
    tie  = models.PositiveIntegerField(default=0)
    total_points = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.team.name   
   

cricket/views.py
from django.shortcuts import render
from .models import Match, Team, Player, Point
from django.db.models import Q
from django.core.paginator import EmptyPage,Paginator,PageNotAnInteger
from django.shortcuts import render,get_object_or_404,redirect
from django.db.models import Count

# Create your views here.


def team_list(request):
    team_list = Team.objects.all()
    paginator=Paginator(team_list, 10)
    page_number=request.GET.get('page')
    try:
        team_list=paginator.page(page_number)
    except PageNotAnInteger:
        team_list=paginator.page(1)
    except EmptyPage:
        team_list=paginator.page(paginator.num_pages)
    return render(request, 'index.html', {'team_list':team_list})


def team_detail(request, pk):
    team_obj = Team.objects.get(id=pk)
    player_obj = Player.objects.filter(team = team_obj)
    return render(request, 'team_detail.html', {'player_obj':player_obj,'team':team_obj})

def fixture(request):
    match_obj = Match.objects.all().order_by('created_at')
    print(match_obj)
    fixture = []
    for match in match_obj:
        fixture.append(match)
    print(fixture)
    return render(request, 'fixture.html', {'match_obj':fixture})  

def points_table(request):
    points_obj = Point.objects.all().order_by('-won')
    print(points_obj)
    points = []
    for point in points_obj:
        points.append(point)
    print(points)
    return render(request, 'points.html', {'points':points})  

templates/fixture.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Fixtures</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static "vendor/bootstrap/css/bootstrap.min.css"%}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static "css/shop-homepage.css"%}" rel="stylesheet">


</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">Home</a>
      <a class="navbar-brand" href="/matches">Fixtures</a>
      <a class="navbar-brand" href="/points">Points</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Match List</h1>
       

      </div>
      <!-- /.col-lg-3 -->

        <div class="row">
        
        <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Team One</th>
      <th scope="col">Between</th>
      <th scope="col">Team Two</th>
    </tr>
  </thead>
  <tbody>
  {% for matches in match_obj %}
    <tr>
    
    <td> <a href="{% url 'cricket:team_detail'  pk=matches.team1.id %}">
    <img class="card-img-top" src={{matches.team1.logo.url}} alt="" width="200px" height="250px"></a></td>
      <th scope="row"><h2>VS </h2>
      <br>
      Date: {{matches.date}}<br>
      Winner :{{matches.winner}}<br>
      Result :{{matches.description}}<br></th>

      <td><a href="{% url 'cricket:team_detail'  pk=matches.team2.id %}">
      <img class="card-img-top" src={{matches.team2.logo.url}} alt="" width="200px" height="250px"></a>
      </td>
      
      
    </tr>
 
{% endfor %}  
  </tbody>
</table>
         
        </div>
        <!-- /.row -->
</div>
      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
  <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
  

</body>

</html>

templates/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Homepage</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static "vendor/bootstrap/css/bootstrap.min.css"%}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static "css/shop-homepage.css"%}" rel="stylesheet">


</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="">Home</a>
      <a class="navbar-brand" href="/matches">Fixtures</a>
      <a class="navbar-brand" href="/points">Points</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          
          {% comment %} <li class="nav-item ">
                  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        
       <form class="form-inline my-2 my-lg-0" method="GET" action="">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{request.GET.q}}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
                  </div>
                 </li> {% endcomment %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Team List</h1>
       

      </div>
      <!-- /.col-lg-3 -->

        <div class="row">
         {% for team in team_list%}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{% url 'cricket:team_detail'  pk=team.id %}">
              <img class="card-img-top" src={{ team.logo.url }} alt="" width="200px" height="250px"></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{% url 'cricket:team_detail'  pk=team.id %}">{{ team.name }}</a>
                </h4>
                <p class="card-text">{{ team.description|truncatewords_html:20}}</p>
              </div>
            </div>
          </div>
        {% endfor %}
        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
{%include 'pagination.html' with page=team_list %}
  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
  <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
  

</body>

</html>

templates/pagination.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item ">
      {% if page.has_previous%}
      <a class="page-link" href="?page={{page.previous_page_number}}" tabindex="-1">Previous</a>
      {% endif %}
    </li>
    <li class="page-item"><a class="page-link" href="{{page.number}} of {{page.paginator.num_pages}}">{{page.number}}</a></li>

    <li class="page-item">
        {% if page.has_next%}
      <a class="page-link" href="?page={{page.next_page_number}}">Next</a>
      {% endif %}
    </li>
  </ul>
</nav>
  </body>
</html>

templates/points.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Points</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static "vendor/bootstrap/css/bootstrap.min.css"%}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static "css/shop-homepage.css"%}" rel="stylesheet">


</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">Home</a>
      <a class="navbar-brand" href="/matches">Fixtures</a>
      <a class="navbar-brand" href="/points">Points</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Points Table</h1>
       

      </div> 
      <!-- /.col-lg-3 -->

        <div class="row">
        
<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Match.No</th>
      <th scope="col">Team Name</th>
      <th scope="col">Played</th>
      <th scope="col">Win</th>
      <th scope="col">Lost</th>
      <th scope="col">Tie</th>
      <th scope="col">Points</th>
    </tr>
  </thead>
  <tbody>
  {% for point in points %}
    <tr>
    <td> {{point.id}} </td>
    <td> {{point.team.name}}</td>
      <td scope="row">
       {{point.play}}<br><br>
      <td>{{point.won}}</td>
      <td>{{point.lost}}</td>
      <td>{{point.tie}}</td>
      <td>{{point.total_points}}</td>
      </td>
      
      
    </tr>
 
{% endfor %}  
  </tbody>
</table>
         
        </div>
        <!-- /.row -->
</div>
      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
  <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
  

</body>

</html>

templates/team_detail.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Detail</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static "vendor/bootstrap/css/bootstrap.min.css"%}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static "css/shop-homepage.css"%}" rel="stylesheet">


</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">Home</a>
       <a class="navbar-brand" href="/matches">Fixtures</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          
          
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-4">

        <h3 class="my-4">{{team.name}}</h3>
       

      </div>
      <!-- /.col-lg-3 -->

        <div class="row">
        
         {% for player in player_obj%}
          <div class="col-lg-3 col-md-6 mb-4">
            <div class="card h-100">
              
              <img class="card-img-top" src={{ player.image.url }} alt="" width="75px" height="175px">
              <div class="card-body">
                <h4 class="card-title">
                  {{ player.first_name }} {{ player.last_name }}
                </h4>
                <p class="card-text">{{ player.description|truncatewords_html:10}}</p>
              </div>
               <div class="card-footer">
                <small class="text-muted">
                Age : {{player.age}} <br>
                Born : {{player.dob}}<br>
                Country : {{player.country}}

                </small>
              </div> 
            </div>
          </div>
        {% endfor %}
        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
  <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
  {% comment %} <script src="static/vendor/jquery/jquery.min.js"></script>
  <script src="static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script> {% endcomment %}

</body>

</html>